# Generated by Django 3.1.3 on 2020-12-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prodName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='prodPrice',
            field=models.IntegerField(default='', max_length=5),
        ),
    ]
