# Generated by Django 3.1.3 on 2020-12-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201214_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodDesc',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='prodImg',
            field=models.ImageField(default='', upload_to='static/shop'),
        ),
    ]
