# Generated by Django 3.1.3 on 2020-12-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201216_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodImg',
            field=models.ImageField(default='', upload_to='shop/static/shop'),
        ),
    ]
